name: Build

on: push

jobs:
  build:
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24.4"

      - name: Build
        run: go build

      - name: Test
        run: go test ./test
